name: learn-github-actions
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Any prerequisite steps
      - uses: actions/checkout@main
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install and build
        run: |
          npm install
          npm run mdcopy

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Remove File
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 10.x
      # - name: npm install and build
      #   run: |
      #     npm install
      #     npm run rmcopy


